### ISSUE TITLE
rimraf error in the latest 3.2.4 version

### ISSUE THREAD

**Issue by RobCC** [webos-tools/cli#43]
# Summary

With the latest release of `3.2.4` we get the following error

```
TypeError: rimraf is not a function
```

`rimraf` was updated to v6, but since v5 they [removed the default export](https://github.com/isaacs/rimraf/blob/main/CHANGELOG.md#50).

The error comes from the default import in [package.js](https://github.com/webos-tools/cli/blob/main/lib/package.js#L22)

```js
 rimraf = require('rimraf'),
```

# Environment
- OS: macOS Tahoe 26.5
- webOS CLI (ares-*): 3.2.4
- Node.js: v24.14.0

**Comment by remisture** [comment]
> ares-package ERR! uncaughtException TypeError: rimraf is not a function

Any chance of fixing this @gigwanlee? `3.2.3` doesn't work with Node 22+ and `3.2.4` is broken.

**Comment by cscd98** [comment]
Please fix this LG

**Comment by dwlee-collab** [comment]
Hello, and thank you all for reporting this.

We are the webOS CLI team at LG Electronics, and we apologize for the inconvenience this has caused to your packaging workflow. We have reproduced the issue and are treating it as our top priority.

Root cause
In 3.2.4, the rimraf dependency was updated to v6. As of v5, rimraf no longer provides a default export, while our packaging code still calls it in the previous (callback) form, which results in TypeError: rimraf is not a function.

Immediate workaround
Until the fix is released, you can restore packaging by pinning rimraf to 3.0.2 within your installed CLI:

npm ls -g @webos-tools/cli
cd "$(npm root -g)/@webos-tools/cli"
npm install rimraf@3.0.2

Please use version 3.0.2 specifically (not v4 or v5). Our packaging code relies on the callback signature, and 3.0.2 is the last release that supports both the default export and the callback API.

Fix
We are preparing a patch release that resolves this issue (aligned with the approach in #44), validated on Node.js 24. We will post the exact version number in this thread as soon as it is published to npm.

Thank you for your patience and for the detailed reports.

Best regards,
The webOS CLI Team, LG Electronics

**Comment by dwlee-collab** [comment]
Hello,

Thank you for your patience. We are happy to inform you that the issue has been resolved in v3.2.5.

Fixed in v3.2.5:
Fixed an issue where ares-package command failed due to rimraf v6 default export changes. The CLI now uses named export and Promise API for compatibility with rimraf v6.

How to update:
npm install -g @webos-tools/cli@latest

We appreciate your detailed reports and feedback.

Best regards,
The webOS CLI Team, LG Electronics
